name: Java CI with Gradle # workflow 이름

# event 정의
on:
  pull_request:
    # main branch에 PR 이벤트가 일어날 경우 해당 action 트리거
    branches: [ main ]

jobs:
  build:

    # 우분투 최신버전 가상환경 사용
    runs-on: ubuntu-latest

    steps:
    # 프로젝트 코드 checkout
    - name: Checkout
      uses: actions/checkout@v2

    # Github Action이 실행될 OS에 Java 설치
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build
      
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2.1.0
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./build/reports/jacoco/test/jacocoTestReport.xml
